x = [10 20 40 80];
% Numbers iterations 
n_Newton = [2 2 2 2];
n_LScheme = [6 6 6 6];
% Residual final time step
residual_Newton = [4.88e-04, 1.13e-06, 6.07e-12];
residual_LScheme = [4.88e-04, 1.52e-04, 4.77e-05, 1.50e-05, 4.70e-06, 1.48e-06, 4.64e-07];

figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot(x, n_Newton, '--+', x, n_LScheme, '--*'),...
    xlabel('1/dx', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times'), ylabel('Number Iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times') ,...
title('Total number of iterations, unsaturated domain'),...
    legend({'Newton','L-Scheme'},...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times',...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',17,...
'FontName','Times')
axis([10 80 1 7])


figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot((1:3), log(residual_Newton), '--+', (1:7), log(residual_LScheme), '--*'),...
    xlabel('1/dx', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times'), ylabel('Pressure residuals', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times') ,...
title('Logarithmic plot of the residuals, unsaturated domain'),...
    legend({'Newton','L-Scheme'},...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times',...
    'Location','NorthEast');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',17,...
'FontName','Times')

% variably saturated domain
n_Newton = [0 0 0 0];
n_LScheme = [6 6 6 6];
% Residual final time step
residual_Newton = [4.88e-04, 2.59e-01];
residual_LScheme = [4.88e-04, 1.52e-04, 4.77e-05, 1.50e-05, 4.70e-06, 1.48e-06, 4.64e-07];

figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot(x, n_Newton, '--+', x, n_LScheme, '--*'),...
    xlabel('1/dx', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times'), ylabel('Number Iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times') ,...
title('Total number of iterations, variably saturated domain'),...
    legend({'Newton','L-Scheme'},...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times',...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',17,...
'FontName','Times')
axis([10 80 1 7])

figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot([1 2], log(residual_Newton), '--+', (1:7), log(residual_LScheme), '--*'),...
    xlabel('1/dx', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times'), ylabel('Pressure residuals', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times') ,...
title('Logarithmic plot of the residuals, variably saturated domain'),...
    legend({'Newton','L-Scheme'},...
'interpreter','latex',...
'FontSize',17,...
'FontName','Times',...
    'Location','NorthEast');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',17,...
'FontName','Times')
